---
name: Verifying Installation

on:
  push:
    branches:
      - main

jobs:
  verify_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and Install
        run: |
          make clean install
          next-prayer --version
